variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/webstatus/*
    - deploy/aro/openshift-templates/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
      - job: WebStatusDeployment
        displayName: 'Web Status Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc process -f ./deploy/aro/openshift-templates/webstatus-deploy-template.yml -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) -p WEB_MVC_HC_URL=$(WebMvcHc) -p WEB_SPA_HC_URL=$(WebSpaHc) -p WEB_SHOPPING_AGGREGATOR_HC_URL=$(WebShoppingAggregatorHc) -p MOBILE_SHOPPING_AGGREGATOR_HC_URL=$(MobileShoppingAggregatorHc) -p ORDERING_API_HC_URL=$(OrderingApiHc) -p BASKET_API_HC_URL=$(BasketApiHc) -p CATALOG_API_HC_URL=$(CatalogApiHc) -p IDENTITY_API_HC_URL=$(IdentityApiHc) -p MARKETING_API_HC_URL=$(MarketingApiHc) -p LOCATIONS_API_HC_URL=$(LocationsApiHc) -p PAYMENT_API_HC_URL=$(PaymentApiHc) -p ORDERING_SIGNALR_HUB_HC_URL=$(OrderingSignalRHubHc) -p ORDERING_BACKGROUND_TASKS_HC_URL=$(OrderingBackgroundTasksHc) | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Web Status OpenShift DeploymentConfig and Service'