variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/mobileshoppingapigw/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
      - template: ../azure-devops-templates/api-gw-deploy.yml
        parameters:
          AppName: mobileshoppingapigw
          AppTitle: 'Mobile Shopping API Gateway'