variables:
  RedisHostname: redis.$(OpenShiftProject).svc
  RabbitMqHostname: rabbitmq.$(OpenShiftProject).svc
  SqlHostName: mssql-server-linux.$(OpenShiftProject).svc
  MongoConnectionString: mongodb://mongo.$(OpenShiftProject).svc
  PublicHostName: eshop$(EnvironmentName)
  IdentityApiHostName: identityapi.$(OpenShiftProject).svc
  IdentityPublicHostName: identity$(EnvironmentName)
  IdentityUrlExternal: https://$(IdentityPublicHostName)
  IdentityApiUrl: http://$(IdentityApiHostName):8080
  IdentityApiHc: $(IdentityApiUrl)/hc
  BasketApiHostName: basketapi.$(OpenShiftProject).svc
  BasketApiUrl: http://$(BasketApiHostName):8080
  BasketApiGrpcUrl: http://$(BasketApiHostName):8081
  BasketApiHc: $(BasketApiUrl)/hc
  CatalogApiHostName: catalogapi.$(OpenShiftProject).svc
  CatalogApiUrl: http://$(CatalogApiHostName):8080
  CatalogApiGrpcUrl: http://$(CatalogApiHostName):8081
  CatalogApiUrlExternal: https://$(CatalogPublicHostName)
  CatalogApiHc: $(CatalogApiUrl)/hc
  PicBaseUrl: $(CatalogApiUrlExternal)/api/v1/catalog/items/[0]/pic/
  LocationsApiHostName: locationsapi.$(OpenShiftProject).svc
  LocationsApiUrl: http://$(LocationsApiHostName):8080
  LocationsApiHc: $(LocationsApiUrl)/hc
  LocationsDbName: LocationsDb
  CampaignDetailFunctionUri:
  MarketingApiHostName: marketingapi.$(OpenShiftProject).svc
  MarketingApiUrl: http://$(MarketingApiHostName):8080
  MarketingApiHc: $(MarketingApiUrl)/hc
  MarketingDbName: MarketingDb
  OrderingApiHostName: orderingapi.$(OpenShiftProject).svc
  OrderingApiUrl: http://$(OrderingApiHostName):8080
  OrderingApiGrpcUrl: http://$(OrderingApiHostName):8081
  OrderingApiHc: $(OrderingApiUrl)/hc
  OrderingSignalRHubHostName: orderingsignalrhub.$(OpenShiftProject).svc
  OrderingSignalRHubUrl: http://$(OrderingSignalRHubHostName):8080
  OrderingSignalRHubHc: $(OrderingSignalRHubUrl)/hc
  OrderingBackgroundTasksHostName: orderingbackgroundtasks.$(OpenShiftProject).svc
  OrderingBackgroundTasksUrl: http://$(OrderingBackgroundTasksHostName):8080
  OrderingBackgroundTasksHc: $(OrderingBackgroundTasksUrl)/hc
  PaymentApiHostName: paymentapi.$(OpenShiftProject).svc
  PaymentApiUrl: http://$(PaymentApiHostName):8080
  PaymentApiGrpcUrl: http://$(PaymentApiHostName):8081
  PaymentApiHc: $(PaymentApiUrl)/hc
  MobileShoppingAggregatorHostName: mobileshoppingaggregator.$(OpenShiftProject).svc
  MobileShoppingAggregatorUrl: http://$(MobileShoppingAggregatorHostName):8080
  MobileShoppingAggregatorHc: $(MobileShoppingAggregatorUrl)/hc
  WebShoppingAggregatorHostName: webshoppingaggregator.$(OpenShiftProject).svc
  WebShoppingAggregatorUrl: http://$(WebShoppingAggregatorHostName):8080
  WebShoppingAggregatorHc: $(WebShoppingAggregatorUrl)/hc
  WebhooksApiHostName: webhooksapi.$(OpenShiftProject).svc
  WebhooksApiUrl: http://$(WebhooksApiHostName):8080
  WebhooksWebClientHostName: webhookclient.$(OpenShiftProject).svc
  WebhooksWebClientUrl: http://$(WebhooksWebClientHostName):8080
  WebhooksToken: 6168DB8D-DC58-4094-AF24-483278923590
  WebSpaUrl: https://eshop-spa$(EnvironmentName)
  WebSpaHc: $(WebSpaUrl)/hc
  WebMvcUrl: https://$(PublicHostName)
  WebMvcHc: $(WebMvcUrl)/hc
  WebShoppingApiGatewayHostName: webshoppingapigw.$(OpenShiftProject).svc
  WebShoppingApiGatewayUrl: http://$(WebShoppingApiGatewayHostName):8080