variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/web-spa/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
      - job: WebSpaDeployment
        displayName: 'Web SPA Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc process -f ./deploy/aro/web-spa/webspa-deploy-template.yml -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) -p IDENTITY_URL_EXTERNAL=$(IdentityUrlExternal) -p WEB_SHOPPING_API_GATEWAY_URL=$(WebShoppingApiGatewayUrl) -p MARKETING_API_URL=$(MarketingApiUrl) -p IDENTITY_API_HC_URL=$(IdentityApiHc) -p ORDERING_SIGNALR_HUB_URL=$(OrderingSignalRHubUrl) | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Web SPA OpenShift DeploymentConfig and Service'