variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/basket-api/*
    - deploy/aro/openshift-templates/*
resources:
  pipelines:
    - pipeline: BasketApiBuild
      source: Basket-API-Build
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: $(OpenShiftProject)
      EnvironmentName: dev
    jobs:
      - job: Configuration_Deployment
        displayName: 'Configuration Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc process -f ./deploy/aro/openshift-templates/identityapi-deploy-template.yml -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) -p WEB_SPA_URL= -p WEB_MVC_URL= -p LOCATION_API_URL= -p MARKETING_API_URL= -p BASKET_API_URL= -p ORDERING_API_URL= -p MOBILE_SHOPPING_AGGREGATOR_URL= -p WEB_SHOPPING_AGGREGATOR_URL= -p WEBHOOKS_API_URL= -p WEBHOOKS_WEB_CLIENT_URL= | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Identity API OpenShift DeploymentConfig and Service'