variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/basket-api/*
    - deploy/aro/openshift-templates/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: dev
    jobs:
      - job: Configuration_Deployment
        displayName: 'Identity API Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc process -f ./deploy/aro/openshift-templates/identityapi-deploy-template.yml -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) -p WEB_SPA_URL=$(WebSpaUrl) -p WEB_MVC_URL=$(WebMvcUrl) -p LOCATION_API_URL=$(LocationsApiUrl) -p MARKETING_API_URL=$(MarketingApiUrl) -p BASKET_API_URL=$(BasketApiUrl) -p ORDERING_API_URL=$(OrderingApiUrl) -p MOBILE_SHOPPING_AGGREGATOR_URL=$(MobileShoppingAggregatorUrl) -p WEB_SHOPPING_AGGREGATOR_URL=$(WebShoppingAggregatorUrl) -p WEBHOOKS_API_URL=$(WebhooksApiUrl) -p WEBHOOKS_WEB_CLIENT_URL=$(WebhooksWebClientUrl) | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Identity API OpenShift DeploymentConfig and Service'