apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${TEMPLATE_NAME}
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: ${TEMPLATE_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Rolling
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
          - env:
              - name: IdentityUrlExternal
                value: ${IDENTITY_URL_EXTERNAL}
              - name: SpaClient
                value: ${WEB_SPA_URL}
              - name: XamarinCallback
                value: 
              - name: MvcClient
                value: ${WEB_MVC_URL}
              - name: LocationApiClient
                value: ${LOCATION_API_URL}
              - name: MarketingApiClient
                value: ${MARKETING_API_URL}
              - name: BasketApiClient
                value: ${BASKET_API_URL}
              - name: OrderingApiClient
                value: ${ORDERING_API_URL}
              - name: MobileShoppingAggClient
                value: ${MOBILE_SHOPPING_AGGREGATOR_URL}
              - name: WebShoppingAggClient
                value: ${WEB_SHOPPING_AGGREGATOR_URL}
              - name: WebhooksApiClient
                value: ${WEBHOOKS_API_URL}
              - name: WebhooksWebClient
                value: ${WEBHOOKS_WEB_CLIENT_URL}
              - name: ConnectionString
                valueFrom:
                  secretKeyRef:
                    key: ConnectionString
                    name: identity-db-connection-secret
            image: docker-registry.default.svc:5000/${IMAGE_REGISTRY_PROJECT_NAME}/${APPLICATION_NAME}:latest
            imagePullPolicy: Always
            name: ${APPLICATION_NAME}
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true 
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            name: ${APPLICATION_NAME}:latest
            namespace: ${IMAGE_REGISTRY_PROJECT_NAME}
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: ${TEMPLATE_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: identityapi
- description: The OpenShift project name that is hosting the image registry.
  displayName: Image Registry Project Name
  name: IMAGE_REGISTRY_PROJECT_NAME
  required: true
- description: The template name.
  displayName: Template Name
  name: TEMPLATE_NAME
  required: true
  value: identityapi-deploy-template
- description: The external URL of the Identity endpoint
  displayName: Identity URL External
  name: IDENTITY_URL_EXTERNAL
  required: true
- description: The cluster internal URL of the Web SPA endpoint
  displayName: Web SPA URL
  name: WEB_SPA_URL
  required: true
- description: The cluster internal URL of the Web MVC endpoint
  displayName: Web MVC URL
  name: WEB_MVC_URL
  required: true
- description: The cluster internal URL of the Location API endpoint
  displayName: Location API URL
  name: LOCATION_API_URL
  required: true
- description: The cluster internal URL of the Marketing API endpoint
  displayName: Marketing API URL
  name: MARKETING_API_URL
  required: true
- description: The cluster internal URL of the Basket API endpoint
  displayName: Basket API URL
  name: BASKET_API_URL
  required: true
- description: The cluster internal URL of the Ordering API endpoint
  displayName: Ordering API URL
  name: ORDERING_API_URL
  required: true
- description: The cluster internal URL of the Mobile Shopping Aggregator endpoint
  displayName: Mobile Shopping Aggregator URL
  name: MOBILE_SHOPPING_AGGREGATOR_URL
  required: true
- description: The cluster internal URL of the Web Shopping Aggregator endpoint
  displayName: Web Shopping Aggregator URL
  name: WEB_SHOPPING_AGGREGATOR_URL
  required: true
- description: The cluster internal URL of the Webhooks API endpoint
  displayName: Webhooks API URL
  name: WEBHOOKS_API_URL
  required: true
- description: The cluster internal URL of the Webhooks Client endpoint
  displayName: Webhooks Client URL
  name: WEBHOOKS_WEB_CLIENT_URL
  required: true