apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: catalogapi
  name: catalog-public-route
spec:
  host: __CatalogPublicHostName__
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
      EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
      EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
      ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
      MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
      EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
      CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
      EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
      BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
      K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
      cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
      pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
      eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
      AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
      HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
      9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
      b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
      b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
      CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
      MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
      91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
      RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
      DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
      GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
      LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGNTCCBR2gAwIBAgIIZknmhzdq45gwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
      BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
      GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
      LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
      cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTkwNTA2MTkzNDI2WhcN
      MjAwNTA2MTkzNDI2WjA7MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
      ZWQxFjAUBgNVBAMMDSoubXNmdG5idS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQClIBSluVLVOKnUbpo5t+ZiFgtbpIqkDqrDheS9IO80PFtfWuQA
      moHety1tFyMiCrq0KWms1nxttW9SeNtKSKeucbldxPFZgXMtBYvuxEdCB0qppIBN
      H1B+/bU1+Yad9QJD8VX24zt9ef8uh8PmDHmuQAtWBJu2axUawJpUpZuU3sYBuqwp
      YwVOSF4IzzCh4gYsCGutocaR8gxKYB+q3cBOC1ZXNNqdqg2njxA3WOkkyXdGBxaB
      hAAcLsvy4/qDj+K4RJu7ljnsCD8l6qK2CFqpsvRq2mI9TdT7FzpW7t9QN6x6q516
      x5tm35xpMD7X6nVj7Gqf/iTctABoCnutYNE7AgMBAAGjggLBMIICvTAMBgNVHRMB
      Af8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAOBgNVHQ8BAf8E
      BAMCBaAwOAYDVR0fBDEwLzAtoCugKYYnaHR0cDovL2NybC5nb2RhZGR5LmNvbS9n
      ZGlnMnMxLTEwOTUuY3JsMF0GA1UdIARWMFQwSAYLYIZIAYb9bQEHFwEwOTA3Bggr
      BgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0
      b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRw
      Oi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZp
      Y2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgw
      FoAUQMK9J47MNIMwojPX+2yz8LQsgM4wJQYDVR0RBB4wHIINKi5tc2Z0bmJ1LmNv
      bYILbXNmdG5idS5jb20wHQYDVR0OBBYEFEk2j0lFiJoxmkJ/wDKsfVr6rUu3MIIB
      BAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+4
      43fNDsgN3BAAAAFqjqPxAQAABAMARzBFAiAe6Mpk1ZNrDqHYzA629obBkmtH6Ysv
      VFYKp3i9hx/l9wIhANj6rlKP3BohnA7cKtZv6VZVAChlgqjf4eUhyR6Z8hTRAHYA
      Xqdz+d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFqjqP12AAABAMARzBF
      AiEA0sdbYqstHo7U/Zia+zcJsQ/dc8/irFjwsiqmtZthd8wCIFg5KLqvL8dUTEAa
      GsDQF/CdGldJkg7fj4yVNjfx7px9MA0GCSqGSIb3DQEBCwUAA4IBAQAXfk++mgc5
      hGxiDgMV0yior1MCip4ieENUbQeXkeizasNKkEz5Tu5uvoP9J+gNjecgG1WII+4O
      QNiHv1/OqgevEM/n7Ey1R5VOh2usboeA5JN+G51MpeNAs6t1i0cdlfVDMhNcbmCN
      y6JY92PJKbUi+RC0UjkBN3IIMrMeTJfnRNBNBbB75OimnFSJnYWX6Xzsfz9x1Agv
      TQ4iYstl07Dcg/VquFORikDenbbbMj1ImzPcNPOhdd7BdZDD8KzfYcqUWgX9qsPT
      XXS0sgTed9+2lpkaTcOImeI1zftIEx/j7PMNZbx3fc5WIau+QDLorzEaAVdTYcpB
      PfB3dFtWPW0U
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClIBSluVLVOKnU
      bpo5t+ZiFgtbpIqkDqrDheS9IO80PFtfWuQAmoHety1tFyMiCrq0KWms1nxttW9S
      eNtKSKeucbldxPFZgXMtBYvuxEdCB0qppIBNH1B+/bU1+Yad9QJD8VX24zt9ef8u
      h8PmDHmuQAtWBJu2axUawJpUpZuU3sYBuqwpYwVOSF4IzzCh4gYsCGutocaR8gxK
      YB+q3cBOC1ZXNNqdqg2njxA3WOkkyXdGBxaBhAAcLsvy4/qDj+K4RJu7ljnsCD8l
      6qK2CFqpsvRq2mI9TdT7FzpW7t9QN6x6q516x5tm35xpMD7X6nVj7Gqf/iTctABo
      CnutYNE7AgMBAAECggEAMPLzG/N1gh6TfZUx48VHprD5OffrX1m3tlFFLumJ71ar
      EXfMmf8zW3W6ohmXQRqkIQ8bs/A7H3yG3RBVlU43Yud0dz8P+qP8pA5+Xk/R/dlS
      gTpyDCqpvpNv+emXxdBhFQoAHTlcI8Sb6Eu3v0TYd1al5aBlFmzk6zLILSqQlc7/
      e+lU+5wLD9mh99efrOfNY5t7ajdX9fEAL2D39N+88LN3qMyHhuEMgiRMq8uEkYj6
      nFjKRZ3vE9v+EEJ04gS/HL8gsAKsVG5XDJpUqJv3Pwn1BYrXM0oaPiRb79oP2/8G
      jo3Xyozxw8Vy82dp7UAPxfCcNhSlAGR3w37bCYdpNQKBgQDma7Q45qGMgTNOUl3t
      wjXEMmxZiql8P2ltJBZkpuxwH22mN5a+UlWVrn5s879wn0YNoqqn9mwHHGqZzjlF
      aL0LiH4Bb6yQk4p2oK+gcHii6y6RGYUZY8VxTPG2IVUwjW8uXOSe9fE/ONCrAwex
      4vNvBhELyHBE3eJN9iBcmzLdtQKBgQC3dMFUpPH+oU/IB29S7gQ87DrbFGR6t+7G
      tzcjwaVFIkHJE94e/X3CyK/8SAf4UDRQibF0w6JgdLucqGR1OohmntmNafwlBoU1
      ehItBqN99k6EzrxaePdeB9X29CEih0Nm+eJK9hKOUqlsQ+LkP0BlK4IlS2+2F2bO
      43DsdXvJLwKBgQC11pNQQDmHD0L08S1s/1G89mnpM/NSuRwy5ELDxbNbPIIkpUPS
      CFnAGQduZeFTOG5pPlDc4iwYZIV/wW4S53ggzONbsMyG/9hKi75tp7ScJWsHWRNf
      mQvswOMTbzSybzspZGeLRt3OncCW5HpDGK4xlKEJInHu9werrKuXSWcX7QKBgEkq
      JkR0uBJeESxsUqiXRldpuxtOabhLjM3xmesHurr0q5ne85IWdMZvNUh/DbapfgO0
      tnIj56liRMR4n//kxStwJMFySF4X2J54PbF5WVDOH4h1zsaiQb1dkKa5vFFB8s6p
      z+cndkUOkIUeGen/k9YFYRUwna/Ya2cNbCbRv/l/AoGBANf1TAe2LcXfrwjzEj8q
      XDefdSH3jktoVmfMGS3f1OcRbj4LSWJ8eZwVzBF4mKVXVxzdsmomDVdmw5tBuscG
      4bhEZuHhqm+Mz5QabiWqZp2pgcleZpTYxY0WyDcXewsHbuHF4OzcdqtN4acTiaI3
      LkTDmFEdPOIRkejfTDbm7oWJ
      -----END PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: catalogapi
    weight: 100
  wildcardPolicy: None