variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/mobilemarketingapigw/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
      - job: MobileMarketingApiGatewayDeployment
        displayName: 'Mobile Marketing API Gateway Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
          displayName: 'Replace tokens in envoy.yaml'
          inputs:
            sourcePath: ./deploy/aro/mobilemarketingapigw
            filePattern: envoy.yaml
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc delete configmap mobilemarketingapigw-config-map'
          failOnStderr: false
          displayName: 'Delete Envoy ConfigMap'
        - script: 'oc create configmap mobilemarketingapigw-config-map --from-file=./deploy/aro/mobilemarketingapigw/envoy.yml'
          failOnStderr: true
          displayName: 'Create Envoy ConfigMap'
        - script: 'oc process -f ./deploy/aro/apigw-templates/apigw-deploy-template.yml -p APPLICATION_NAME=mobilemarketingapigw -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Mobile Marketing API Gateway OpenShift DeploymentConfig and Service'