variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/mobilemarketingapigw/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
    - template: ../azure-devops-templates/api-gw-deploy.yml
      parameters:
        AppName: mobilemarketingapigw
        AppTitle: 'Mobile Marketing API Gateway'