variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/webmarketingapigw/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -dev.msftnbu.com
    jobs:
      - template: ./deploy/aro/azure-devops-templates/api-gw-deploy.yml
        parameters:
          AppName: webmarketingapigw
          AppTitle: 'Web Marketing API Gateway'