variables:
  OpenShiftServiceConnection: 'OpenShift on ARO'
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - deploy/aro/mobileshoppingagg/*
stages:
  - stage: development
    displayName: Development
    variables:
      OpenShiftProject: development
      SourceImageRegistryProjectName: development
      EnvironmentName: -development.apps.cluster-k4pz2.k4pz2.sandbox1929.opentlc.com
    jobs:
      - job: MobileShoppingAggregatorDeployment
        displayName: 'Mobile Shopping Aggregator Deployment'
        variables:
        - template: ../azure-devops-templates/variables.yml
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: redhat.openshift-vsts.oc-setup-task.oc-setup@2
          displayName: 'Setup Openshift CLI'
          inputs:
            openshiftService: $(OpenShiftServiceConnection)
        - script: 'oc project $(OpenShiftProject)'
          failOnStderr: true
          displayName: 'Set OpenShift Project Context'
        - script: 'oc process -f ./deploy/aro/mobileshoppingagg/mobileshoppingagg-deploy-template.yml -p IMAGE_REGISTRY_PROJECT_NAME=$(SourceImageRegistryProjectName) -p BASKET_API_URL=$(BasketApiUrl) -p CATALOG_API_URL=$(CatalogApiUrl) -p ORDERING_API_URL=$(OrderingApiUrl) -p IDENTITY_API_URL=$(IdentityApiUrl) -p BASKET_API_GRPC_URL=$(BasketApiGrpcUrl) -p CATALOG_API_GRPC_URL=$(CatalogApiGrpcUrl) -p ORDERING_API_GRPC_URL=$(OrderingApiGrpcUrl) -p CATALOG_API_HC_URL=$(CatalogApiHc) -p ORDERING_API_HC_URL=$(OrderingApiHc) -p IDENTITY_API_HC_URL=$(IdentityApiHc) -p BASKET_API_HC_URL=$(BasketApiHc) -p MARKETING_API_HC_URL=$(MarketingApiHc) -p PAYMENT_API_HC_URL=$(PaymentApiHc) -p LOCATION_API_HC_URL=$(LocationsApiHc) -p IDENTITY_URL_EXTERNAL=$(IdentityUrlExternal) | oc apply -f-'
          failOnStderr: true
          displayName: 'Ensure Mobile Shopping Aggregator OpenShift DeploymentConfig and Service'